main/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'main.views.index'),
    (r'^register/$','main.views.register'),
)

pp/urls.py
from django.conf.urls import patterns, include, url
from main import views

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'main.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^adminUsers/', views.adminUsers, name='adminUsers'),
    url(r'^adminCategories/', views.adminCategories, name='adminCategories'),
    url(r'^moderator/', views.moderator, name='moderator'),
    url(r'^categories/', views.categories, name='categories'),
    url(r'^(?P<cat_id>\d+)/projects/', views.projects, name='projects'),
    url(r'^projects/', views.projects, name='projects'),
    url(r'^project/(?P<pro_id>\d+)/', views.project, name='project'),
    url(r'^rejestracja/$',views.UserRegister, name='register'),
    url(r'^nowyprojekt/$',views.AddNewProject, name='newproject'),
    url(r'^edytujprojekt/(?P<project_id>\d+)/$',views.EditProject, name='editproject'),
    url(r'^addcoment/(?P<pro_id>\d+)/', views.addcoment, name='addcoment'),
    url(r'^logowanie/$', views.Signin, name='signin'),
    url(r'^wspieranie/(?P<pro_id>\d+)/', views.Support, name='support'),
)

main/models.py
from django.db import models
import datetime


class Category(models.Model):
    name = models.CharField(max_length=80)
    def __str__(self):  # Python 3: def __str__(self):
        return self.name


class User(models.Model):
    login = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=50)
    type = models.IntegerField(default=2)  #type=1 to bedzie uzytkownik zwykly
    ban = models.BooleanField(default=False)
    date_created = models.DateTimeField(
        auto_now_add=True)  #Automatically set the field to now when the object is first created. Useful for creation of timestamps
    last_update = models.DateTimeField(auto_now=True)
    def __str__(self):  # Python 3: def __str__(self):
        return self.login


class Project(models.Model):
    title = models.CharField(max_length=80)
    short_description = models.CharField(
        max_length=160)  #krotki opis projktu,mozeby byc wyswietlany na st glownej, razem z paskiem postepu itd
    full_description = models.TextField()  #pelny opis projektu
    funding_goal = models.DecimalField(max_digits=8, decimal_places=2)  #ilosc pieniedzy planowanych do zebrania
    money_raised = models.DecimalField(default=0, max_digits=8, decimal_places=2)  #ilosc pieniedzy juz zebranych
    deadline = models.DateField(default=datetime.date.today)  #data zakonczenia projektu
    date_created = models.DateTimeField(
        auto_now_add=True)  #Automatically set the field to now when the object is first created. Useful for creation of timestamps
    last_update = models.DateTimeField(
        auto_now=True)  #Automatically set the field to now every time the object is saved. Useful for 'last-modified' timestamps
    rating = models.IntegerField(default=0) #ocena projektu
    ban = models.BooleanField(default=False)
    visit_counter = models.IntegerField(default=0)
    category = models.ForeignKey(Category)
    user = models.ForeignKey(User)
    def __str__(self):  # Python 3: def __str__(self):
        return self.title


class Perk(models.Model):
    # poziomy wsparcia projektu i przewidziane nagrody za wsparcie taka suma pieniedzy
    amount = models.DecimalField(max_digits=8, decimal_places=2)  #ilosc pieniedzy w danym poziomie
    title = models.CharField(max_length=80)  #tytul, nazwa poziomu
    description = models.TextField()  #opis poziomu
    number_available = models.IntegerField(blank=True)  #blank=True znaczy, ze wartosc moze byc null
    #jesli amount=null, to liczba danej nagrody za wsparcie jest nieograniczona
    project = models.ForeignKey(Project)
    def __str__(self):  # Python 3: def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)
    def __str__(self):  # Python 3: def __str__(self):
        return self.content


class Message(models.Model):
    subject = models.TextField(max_length=80)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    user_from = models.ForeignKey(User, related_name='message_user_from')
    user_to = models.ForeignKey(User, related_name='message_user_to')
    def __str__(self):  # Python 3: def __str__(self):
        return self.subject


class Donation(models.Model):
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)
    perk = models.ForeignKey(Perk)
    def __str__(self):  # Python 3: def __str__(self):
        return self.amount

main/forms.py
from django import forms
from main.models import User, Comment, Category, User, Perk
from django.core.exceptions import ObjectDoesNotExist
import re
from django.core import validators


class UserRegisterForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('login','email','password')
        labels={
            'login': ('Login'),
            'email': ('Email'),
            'password': ('Haslo'),
        }
        widgets={
            'password': forms.PasswordInput()
        }

    confirmpassword = forms.CharField(label='Potwierdz haslo', widget=forms.PasswordInput())



class ProjectRegisterForm(forms.Form):
    title=forms.CharField(label='Nazwa projektu',widget=forms.TextInput(attrs={'class': 'form-control'}))
    short_description=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    funding_goal=forms.IntegerField(label='Oczekiwana kwota wsparcia', widget=forms.NumberInput(attrs={'class': 'form-control','min':'0','max': '1000000', 'step': '10','type':'range','value':'0','onmousemove': 'valuechange()','width': 300}))
    description=forms.CharField(label='Opis projektu', widget=forms.Textarea(attrs={'style': 'visibility: hidden'}))
    category=forms.ModelChoiceField(queryset=Category.objects.all(),label='Kategoria',initial=1)

class ProjectPerks(forms.Form):
    perk_description=forms.CharField(label='Krotki opis progu',widget=forms.Textarea(attrs={'class': 'form-control'}))
    perk_value=forms.IntegerField(label='Oczekiwana kwota wsparcia', widget=forms.NumberInput(attrs={'min':'0','max': '1000000', 'step': '10','type':'range','value':'0','onmousemove': 'perkvaluechange()'}))

class ComentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class Signin(forms.ModelForm):
    class Meta:
        model=User
        fields=('login','password',)

class SupportForm(forms.ModelForm):
    class Meta:
        model=Perk
        fields=('amount',)
        labels={
            'amount' :('Kwota')
        }
amount=forms.DecimalField(label='Kwota', widget=forms.NumberInput)

main/views.py
from datetime import datetime
from django.db.utils import ConnectionDoesNotExist
from main import forms
from django.http import HttpResponse
from django.shortcuts import render_to_response, redirect
from django.template import loader, RequestContext
from main.models import Category, Project, Comment, User, Perk, Donation
from django.db.models import Q, Count
from django.http import HttpResponseRedirect
from django.contrib.sessions.models import Session
import decimal
from decimal import Decimal

def index(request):
    template = loader.get_template('index.html')
    now = datetime.now().date()
    deadline_project_list = Project.objects.filter(deadline__gte=now).order_by('deadline')[:3]
    popular_project_list = Project.objects.filter(deadline__gte=now).order_by('-visit_counter')[:3]
    #wyswietla tylko prjekty niezakonczone, posortowane wzgledem licznika odwiedzin malejąco
    for p in deadline_project_list:
        perc = (p.money_raised / p.funding_goal) * 100
        percentage = int(perc)
        diff = p.deadline - now
        daysLeft = diff.days
        if daysLeft < 0:
            daysLeft = 0
        setattr(p, 'toEnd', daysLeft)
        setattr(p, 'percentage', percentage)

    for p in popular_project_list:
        perc = (p.money_raised / p.funding_goal) * 100
        percentage = int(perc)
        diff = p.deadline - now
        daysLeft = diff.days
        if daysLeft < 0:
            daysLeft = 0
        setattr(p, 'toEnd', daysLeft)
        setattr(p, 'percentage', percentage)

    context = RequestContext(request, {
        'deadline_project_list': deadline_project_list,
        'popular_project_list': popular_project_list,
    })
    return HttpResponse(template.render(context))


def projects(request):
    request.session['user'] = False
    order_by = request.GET.get('order_by', '-visit_counter')
    key = request.GET.get('key', '')
    projects_list = Project.objects.filter(Q(title__contains=key) | Q(full_description__contains=key)).order_by(
        order_by)
    now = datetime.now().date()
    for p in projects_list:
        diff = p.deadline - now
        daysLeft = diff.days
        if daysLeft < 0:
            daysLeft = 0
        setattr(p, 'toEnd', daysLeft)
    template = loader.get_template('projects.html')
    context = RequestContext(request, {
        'projects_list': projects_list,
        'key': key,
    })
    return HttpResponse(template.render(context))


def adminUsers(request):
    template = loader.get_template('admin_users.html')
    context = RequestContext(request)
    return HttpResponse(template.render(context))


def adminCategories(request):
    template = loader.get_template('admin_categories.html')
    context = RequestContext(request)
    return HttpResponse(template.render(context))


def moderator(request):
    template = loader.get_template('moderator.html')
    context = RequestContext(request)
    return HttpResponse(template.render(context))


def categories(request):
    order_by = request.GET.get('order_by', 'name')
    cat_list = Category.objects.annotate(count=Count('project__id')).order_by(order_by)

    template = loader.get_template('categories.html')
    context = RequestContext(request, {
        'cat_list': cat_list,
    })
    return HttpResponse(template.render(context))


def projects(request, cat_id="0"):
    order_by = request.GET.get('order_by', '-visit_counter')
    key = request.GET.get('key', '')
    projects_list = Project.objects.filter(Q(title__contains=key) | Q(full_description__contains=key)).order_by(
        order_by)
    catId = int(cat_id)
    if catId > 0:
        projects_list = Project.objects.filter(category__id=catId).order_by(order_by)
    now = datetime.now().date()
    for p in projects_list:
        diff = p.deadline - now
        daysLeft = diff.days
        if daysLeft < 0:
            daysLeft = 0
        setattr(p, 'toEnd', daysLeft)
    template = loader.get_template('projects.html')
    context = RequestContext(request, {
        'projects_list': projects_list,
        'key': key,
    })
    return HttpResponse(template.render(context))


def project(request, pro_id):
    template = loader.get_template('project.html')
    pro = Project.objects.get(id=int(pro_id))
    coms = Comment.objects.filter(project=pro).order_by('-date_created')
    context = RequestContext(request, {'coms': coms, 'proid': str(pro_id)})
    return HttpResponse(template.render(context))


def UserRegister(request):
    f = forms.UserRegisterForm()
    context = RequestContext(request, {'formset': f})
    if request.method == 'POST':
        f = forms.UserRegisterForm(request.POST)
        if f.is_valid():
            login = f.cleaned_data.get("login")
            email=f.cleaned_data.get("email")
            password = f.cleaned_data.get("password")
            confirmpassword=f.cleaned_data.get("confirmpassword")
            if password == confirmpassword:
                try:
                    us = User.objects.get(login=f.data['login'])
                except:
                    f.save()
                    return redirect('/', request)
                return redirect('/rejestracja')
            else:
                return redirect('/rejestracja')
            return redirect('/', request)
    else:
        return render_to_response('register.html', context)


def AddNewProject(request):
    f = forms.ProjectRegisterForm(prefix='project')
    fr = forms.ProjectPerks(prefix='perk')
    context = RequestContext(request, {'formset': f, 'form1': fr})
    if request.method == 'POST':
        f = forms.ProjectRegisterForm(request.POST, prefix='project')
        fr = forms.ProjectPerks(request.POST, prefix='perk')
        if f.is_valid():
            p = Project()
            p.title = f.cleaned_data['title']
            p.short_description = f.cleaned_data['short_description']
            p.funding_goal = f.cleaned_data['funding_goal']
            p.full_description = f.cleaned_data['description']
            p.category = f.cleaned_data['category']
            p.user_id = 1
            Project.save(p)
            return redirect('/', request)
    else:
        return render_to_response('AddNewProject.html', context)


def EditProject(request, project_id):
    f = forms.ProjectRegisterForm()
    context = RequestContext(request, {'formset': f})
    if request.method == 'POST':
        f = forms.ProjectRegisterForm(request.POST)
        if f.is_valid():
            f.save()
        return redirect('/', request)
    return


def Signin(request):
    if request.method == 'POST':
        c = forms.Signin(request.POST)
        try:
            us = User.objects.get(login=c.data['login'],password=c.data['password'])
        except:
            return redirect('/logowanie')
        request.session['user'] = us.id
        request.session['type'] = us.type
        return redirect('/')
    else:
        f = forms.Signin
        return render_to_response('signin.html', RequestContext(request, {'formset': f}))


def addcoment(request, pro_id):
    if request.method == 'POST':
        c = forms.ComentForm(request.POST)
        coment = Comment()
        coment.project = Project.objects.get(id=int(pro_id))
        coment.content = c.data['content']
        coment.user = User.objects.get(id=1)
        coment.save()
        return redirect('/project/' + str(pro_id))
    else:
        f = forms.ComentForm
        return render_to_response('comment.html', RequestContext(request, {'formset': f}))

def Support(request,pro_id):
    template = loader.get_template('support.html')
    projekt = Project.objects.get(id=int(pro_id))
    perk_list = Perk.objects.filter(project=projekt).order_by('amount')
    zmienna=perk_list[0].amount
    choice_perk_list=Perk.objects.filter(project=projekt).order_by('amount')
    context = RequestContext(request, {
            'perk_list': perk_list,
            'choice_perk_list': choice_perk_list,
            'projekt': projekt,
            'proid': str(pro_id)
            })
    if request.method == 'POST':
        f = forms.SupportForm(request.POST)
        if f.data['amount']:
            if f.is_valid:
               amount=int(f.data['amount'])
               user = request.session.get['user']
               if amount<zmienna:
                   f = forms.SupportForm
                   return render_to_response('support.html', RequestContext(request, {'formset': f}),context)
               else:
                   for perk in perk_list:
                    if perk.amount<=amount:
                        kwota=perk.amount
                        id=perk.id
                        donation = Donation()
                        donation.amount=decimal.Decimal(f.data['amount'])
                        donation.date=datetime.now().date()
                        donation.user= User.objects.get(id=user)
                        donation.project=Project.objects.get(id=pro_id)
                        donation.perk=Perk.objects.get(id=id)
                        donation.save()
            return redirect('/',request)
        else:
            f = forms.SupportForm
            return render_to_response('support.html', RequestContext(request, {'formset': f}),context)
    else:
        f = forms.SupportForm
        return render_to_response('support.html', RequestContext(request, {'formset': f}),context)

main/templates/AddNewProject.html
{% extends "base.html" %}
{% block title %}
Nowy Projekt
{% endblock %}
{% block content %}
    <div>
        <form method="post" action="">
            {% csrf_token %}
            <table style="width: 100%">
                <tr><td style="width: 45%"><label> Nazwa projektu</label>

                <td style="width: 55%">{{ formset.title }}</td>
                </tr>
                <tr></tr>
                <tr><td><label>Krótki opis projektu  </label> </td>
                <td>{{ formset.short_description }}</td></tr>
                <tr></tr>
                <tr><td><label>Kategoria projektu</label></td>
                <td>{{ formset.category }} </td></tr>
                <tr></tr>
                <tr><td><label>Wybierz planowaną kwotę do uzbierania</label>&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td></td></tr>
                <tr><td>{{ formset.funding_goal}}</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <label id="goal">0</label></td></tr>
            </table>
            <br>
            <a>Dodaj progi finansowania</a>
            <div class="perks">
            </div>
            <div>
               <label>Kwota progu finansowania:</label><br>
                {{form1.perk_value}}<label id="perkvalue">0</label>
               <br>
                <label>Opis progu finansowania:</label>
                {{form1.perk_description}}

            </div>
            <label>Pełny opis projektu:</label>
            {{ formset.description}}
            <div>
                <div id="fulldescription"></div>
            </div>
            <input onmousedown="a()" type="submit" class="btn btn-default" value="Zatwierdź">
            <input type="reset" class="btn btn-default" value="Anuluj">
        </form>
    </div>
    <script type="text/javascript">
    var a=function(){ $('#id_project-description').val($('#fulldescription').code()) };
    $(document).ready(function() {
          $('#fulldescription').summernote({
              onImageUpload: a(),
              onfocus: a(),
              onblur: a()
          });
    });
    var valuechange=function(){$('#goal').html($('#id_project-funding_goal').val());}
    var perkvaluechange=function(){$('#perkvalue').html($('#id_perk-perk_value').val());};
    </script>
{% endblock %}

main/templates/addproject.html
{% extends "base.html" %}
{% block title %}
Rejestracja użytkownika
{% endblock %}
{% block content %}
    <div>
        <form method="post" action="">
            {% csrf_token %}
            <table>
                {{ formset }}
                </br>
            </table>
            <input type="submit" class="btn btn-default" value="Zatwierdź">
            <input type="submit" class="btn btn-default" value="Anuluj">
        </form>
    </div>
{% endblock %}

main/templates/admin_categories.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
    Panel admina
{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}admin.css">
<script type="text/javascript">
    function activateTab(pageId) {
        var tabCtrl = document.getElementById('tabCtrl');
        var pageToActivate = document.getElementById(pageId);
        for (var i = 0; i < tabCtrl.childNodes.length; i++) {
            var node = tabCtrl.childNodes[i];
            if (node.nodeType == 1) { /* Element */
                node.style.display = (node == pageToActivate) ? 'block' : 'none';
            }
        }
    }

</script>
    <br>
    <div id="nav">
        <ul>
            <li class="active">
                <a href="">Użytkownicy</a>
            </li>
            <li>
                <a href="">Kategorie</a>
            </li>
        </ul>
    </div>
    <br><br><br>
    <input type="text" width="300">
    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
    <br><br>
    <input type="text" width="300">
    <button type="submit" class="btn btn-default">Dodaj</button>
    <br><br>
    <table>
        <tr>
            <th>ID</th>
            <th>Nazwa</th>
        </tr>
        <tr>
            <td>1</td>
            <td>architektura</td>
            <td>
                <button class="linkButton">Edytuj</button>
                <button class="linkButton">Usuń</button>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>edukacja</td>
            <td>
                <button class="linkButton">Edytuj</button>
                <button class="linkButton">Usuń</button>
            </td>
        </tr>
        <tr>
            <td>3</td>
            <td>film</td>
            <td>
                <button class="linkButton">Edytuj</button>
                <button class="linkButton">Usuń</button>
            </td>
        </tr>
        <tr>
            <td>4</td>
            <td>gry</td>
            <td>
                <button class="linkButton">Edytuj</button>
                <button class="linkButton">Usuń</button>
            </td>
        </tr>
    </table>
{% endblock %}

main/templates/admin_users.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
    Panel admina
{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}admin.css">
    <br>
    <div id="nav">
        <ul>
            <li class="active">
                <a href="">Użytkownicy</a>
            </li>
            <li>
                <a href="">Kategorie</a>
            </li>
        </ul>
    </div>
    <br><br><br>
    <input type="text" width="300">
    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
    <br><br>
    <table>
        <tr>
            <th>ID</th>
            <th>Login</th>
            <th>Email</th>
            <th>Ban</th>
            <th>Uprawnienia</th>
        </tr>
        <tr>
            <td>1</td>
            <td>admin</td>
            <td>admin@admin.pl</td>
            <td>Nie</td>
            <td>administrator</td>
            <td>
                <button class="linkButton">Edytuj</button>
                <button class="linkButton">Zablokuj</button>
                <button class="linkButton">Usuń</button>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>user1</td>
            <td>user1@user.pl</td>
            <td>Nie</td>
            <td>moderator</td>
            <td>
                <button class="linkButton">Edytuj</button>
                <button class="linkButton">Zablokuj</button>
                <button class="linkButton">Usuń</button>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>user2</td>
            <td>user2@user2.pl</td>
            <td>Tak</td>
            <td>użytkownik</td>
            <td>
                <button class="linkButton">Edytuj</button>
                <button class="linkButton">Zablokuj</button>
                <button class="linkButton">Usuń</button>
            </td>
        </tr>
    </table>
{% endblock %}

main/templates/base.html
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>{% block title %}Krałdfanding{% endblock %}</title>

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css">
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <script src="{{ STATIC_URL }}summernote.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}summernote.css"/>
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <link rel="Stylesheet" type="text/css" href="{{ STATIC_URL }}base.css"/>

</head>


<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container" id="gora" style="width: auto;">
        <div class="col-md-2">
            <a class="navbar-brand" href="{% url 'index' %}">Nasza strona</a>
        </div>

        <div class="col-md-5">
            <form class="navbar-form navbar-left" role="search" action="{% url 'projects' %}">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" name="key">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </form>
        </div>

        <div class="col-md-5">
            <ol class="breadcrumb" style="background-color:#97694F">
                {% block rejestracja %}
                <li><a style="color: white" href="{% url 'register' %}">Rejestracja</a></li>
                <li><a style="color: white" href="{% url 'signin' %}">Zaloguj się</a></li>
                {% endblock %}
                <li><a style="color: white" href="#">Jestes zalogowany jako:{% block login %}{% endblock %}</a></li>
            </ol>
        </div>
    </div>
</nav>

<div class="row" style="margin: 5em 1em;">

    <div class="col-md-2">
        <div class="btn-group-vertical">

           <a href="{% url 'projects' %}" class=" btn btn-primary btn-lg active" role="button" style="font-size: 17px;">Projekty</button></a>
  <a href="{% url 'categories' %}" class=" btn btn-info btn-lg active" role="button" style="font-size: 14px;">Kategorie</button></a>
  <a href="{% url 'categories' %}" class=" btn btn-info btn-lg active" role="button" style="font-size: 14px;">Obserwowne</button></a>
  <a href="{% url 'categories' %}" class=" btn btn-info btn-lg active" role="button" style="font-size: 14px;">Utwórz nowy</button></a>
  <a href="{% url 'categories' %}" class=" btn btn-info btn-lg active" role="button" style="font-size: 17px;">Powiadomienia</button></a>
  <a href="{% url 'categories' %}" class=" btn btn-info btn-lg active" role="button" style="font-size: 14px;">Oznacz jako odczytane</button></a>
  <a href="{% url 'categories' %}" class=" btn btn-info btn-lg active" role="button" style="font-size: 17px;">Wiadomosci</button></a>
  <a href="{% url 'categories' %}" class=" btn btn-info btn-lg active" role="button" style="font-size: 14px;">Oznacz jako odczytane</button></a>

        </div>
    </div>
    <div class="col-md-10" style="padding:2em 4em;">{% block content %}{% endblock %}</div>
</div>

<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
    <div class="container" id="gora" style="width: auto;">

        <div class="col-md-1">
            <a class="navbar-brand" href="#">Nasza strona</a>
        </div>
        <div class="col-md-4">
            <ol class="breadcrumb" style="background-color:#97694F">
                <li><a style="color: white" href="#">O nas</a></li>
                <li><a style="color: white" href="#">Regulamin</a></li>
                <li><a style="color: white" href="#">Kontakt</a></li>
                <li><a style="color: white" href="#">Jak to dziala?</a></li>
            </ol>
        </div>

        <div class="col-md-3">
            <form class="navbar-form navbar-left">
                <button type="submit" class="btn btn-default"><span> <img src="{{ STATIC_URL }}fb.gif"> </span></button>
            </form>
            <form class="navbar-form navbar-left">
                <button type="submit" class="btn btn-default"><span> <img src="{{ STATIC_URL }}t.png"> </span></button>
            </form>
        </div>
        <div class="col-md-4">
            Autorzy: M.Dobrzynski, M.Farfulowska, Z.Firlus, P.Zydok, M.Giedzinski, P.Wysocki 2014
        </div>
    </div>
</nav>
</body>
</html>

main/templates/comment.html
{% extends "base.html" %}
{% block title %}
Rejestracja użytkownika
{% endblock %}
{% block content %}
    <div>
        <form method="post" action="">
            {% csrf_token %}
            <table>
                {{ formset }}
                </br>
            </table>
            <input type="submit" class="btn btn-default" value="Zatwierdź">
            <input type="reset" class="btn btn-default" value="Anuluj">
        </form>
    </div>
{% endblock %}

main/templates/new_message.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
    Nowa wiadomość
{% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}user.css">
    <div>
        <form method="post" action="">
            {% csrf_token %}
            <table>
                {{ formset }}
                </br>
            </table>
            <input type="submit" class="btn btn-default" value="Zatwierdź">
            <input type="reset" class="btn btn-default" value="Anuluj">
        </form>
    </div>
{% endblock %}